[book]
authors = ["tovicheung"]
language = "en"
multilingual = false
src = "src"
title = "Tovi's Chemistry Notes"
theme = "theme"

[output.html.fold]
enable = true

[preprocessor.katex]
after = ["links"]
